#ifndef CLOCK_H
#define CLOCK_H

#include <common.h>

#define RCC_BASE_ADDR 0x40023800

typedef struct _RCC {
    _MMAP_REGION RCC_CR;
    _MMAP_REGION RCC_PLLCFGR;
    _MMAP_REGION RCC_CFGR;
    _MMAP_REGION RCC_CIR;
    _MMAP_REGION RCC_AHB1RSTR;
    _MMAP_REGION RCC_AHB2RSTR;
    _RESERVED_
    _RESERVED_
    _MMAP_REGION RCC_AB1RSTR;
    _MMAP_REGION RCC_AB2RSTR;
    _RESERVED_
    _RESERVED_
    _MMAP_REGION RCC_AHB1ENR;
    _MMAP_REGION RCC_AHB2ENR;
    _RESERVED_
    _RESERVED_
    _MMAP_REGION RCC_APB1ENR;
    _MMAP_REGION RCC_APB2ENR;
    _RESERVED_
    _RESERVED_
    _MMAP_REGION AHB1LPENR;
    _MMAP_REGION AHB2LPENR;
    _RESERVED_
    _RESERVED_
    _MMAP_REGION RCC_BDCR;
    _MMAP_REGION RCC_CSR;
    _RESERVED_
    _RESERVED_
    _MMAP_REGION RCC_SSCGR;
    _MMAP_REGION RCC_PLLI2SCFGR;
    _RESERVED_
    _MMAP_REGION RCC_DCKCFGR;
} _RCC __attribute__((aligned(sizeof(_MMAP_REGION))));

static volatile struct _RCC *RCC __attribute__((unused)) = (struct _RCC *) RCC_BASE_ADDR;

#endif
